### ISSUE TITLE
Is the function of data expiration still valid in such case?

### ISSUE THREAD

**Issue by zzc-tongji** [tidwall/buntdb#29] opened 2017-11-15 02:17 UTC
I want to create a database on disk, and let all item expire in 7 days after creating.

Here is the code:

``` go
db.Update(func(tx *buntdb.Tx) error {
		_, _, err = tx.Set("word", "define",
			&buntdb.SetOptions{Expires: true, TTL: time.Duration(7*24) * time.Hour})
		return
})
```

However, the program will not run for such long time. Is the function of data expiration still valid?

Here is the result I expect:

1. Run the program in Nov 1st, add item "A" in the database and then exit. 
2. Run the program in Nov 3rd, add item "B" in the database and then exit.
3. Run the program in Nov 7th. At this time, item "A" and "B" are still existent.
4. Run the program in Nov 9th. At this time, only item "B" is still existent.
5. Run the program in Nov 11th. At this time, non of item "A" and "B" is existent.

Is it possible?

**Comment by 0joshuaolson1** [comment] 2018-04-14 07:52
Look for `exat` in https://github.com/tidwall/buntdb/blob/master/buntdb.go

[I think](https://golang.org/src/time/time.go#L48) it works iff the saving and loading processes see 'normal' wall clock behavior (screw you, Daylight Saving etc.)

One could test: use a one minute TTL, exit the program, load it, and wait.

**Comment by tidwall** [comment] 2018-04-30 12:04
@zzc-tongji

Sorry for the delayed response.

I don't think that BuntDB will work in your case.

When an expiration is added to a key, that key gets marked with a timestamp that's tracked by a background operation. Also the key and it's duration (in seconds) until expiration are logged to disk.

Prior to the application closing, any active keys that are still marked expiration are re-logged to disk with an updated duration. 

Then when the application restarts, the log is read and the keys are again marked. 

The problem is that the on disk expiration value is a duration in seconds, not an absolute date+time.


I'm closing this issue for now because it's a few months old, but feel free to reopen if needed.

Thanks!

**Closed by tidwall** 2018-04-30 12:04 UTC
